{{- define "tm.serviceAccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tm.fullname" . }}
  labels:
    {{- include "tm.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.gsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.gsaEmail | quote }}
  {{- end }}
{{- end -}}
