apiVersion: v2
name: trip
description: Trip + locations + travel plans
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: travelmanager-service
    version: 0.1.0
    repository: file://../_template
